// Code generated by protoc-gen-go.
// source: protobuf/task/task.proto
// DO NOT EDIT!

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	protobuf/task/task.proto

It has these top-level messages:
	Task
	TodayTasksRequest
	TodayTasksResponse
	AddRequest
	AddResponse
	RemoveRequest
	RemoveResponse
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResponseStatus is response status enum.
type ResponseStatus int32

const (
	ResponseStatus_UNKNOWN                ResponseStatus = 0
	ResponseStatus_SUCCESS                ResponseStatus = 1
	ResponseStatus_INTERNAL_ERROR         ResponseStatus = 2
	ResponseStatus_TASK_INVALID_TASK_NAME ResponseStatus = 16
	ResponseStatus_TASK_NOT_FOUND         ResponseStatus = 17
)

var ResponseStatus_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUCCESS",
	2:  "INTERNAL_ERROR",
	16: "TASK_INVALID_TASK_NAME",
	17: "TASK_NOT_FOUND",
}
var ResponseStatus_value = map[string]int32{
	"UNKNOWN":                0,
	"SUCCESS":                1,
	"INTERNAL_ERROR":         2,
	"TASK_INVALID_TASK_NAME": 16,
	"TASK_NOT_FOUND":         17,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}
func (ResponseStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Task holds task information.
type Task struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TaskName  string `protobuf:"bytes,2,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Tags      string `protobuf:"bytes,4,opt,name=tags" json:"tags,omitempty"`
	Notes     string `protobuf:"bytes,5,opt,name=notes" json:"notes,omitempty"`
	NotesMd   string `protobuf:"bytes,6,opt,name=notes_md,json=notesMd" json:"notes_md,omitempty"`
	Date      string `protobuf:"bytes,7,opt,name=date" json:"date,omitempty"`
	Completed bool   `protobuf:"varint,8,opt,name=completed" json:"completed,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Task) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Task) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Task) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Task) GetNotesMd() string {
	if m != nil {
		return m.NotesMd
	}
	return ""
}

func (m *Task) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Task) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

// TodayTasksRequest holds information which can be used
// to filter today task list.
type TodayTasksRequest struct {
	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	Tags     string `protobuf:"bytes,2,opt,name=tags" json:"tags,omitempty"`
}

func (m *TodayTasksRequest) Reset()                    { *m = TodayTasksRequest{} }
func (m *TodayTasksRequest) String() string            { return proto.CompactTextString(m) }
func (*TodayTasksRequest) ProtoMessage()               {}
func (*TodayTasksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TodayTasksRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *TodayTasksRequest) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

// TodayTasksResponse holds today task list.
type TodayTasksResponse struct {
	Tasks  []*Task        `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	Status ResponseStatus `protobuf:"varint,2,opt,name=status,enum=kudu.task.ResponseStatus" json:"status,omitempty"`
}

func (m *TodayTasksResponse) Reset()                    { *m = TodayTasksResponse{} }
func (m *TodayTasksResponse) String() string            { return proto.CompactTextString(m) }
func (*TodayTasksResponse) ProtoMessage()               {}
func (*TodayTasksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodayTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *TodayTasksResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

// AddRequest holds information of task which is going to be added.
type AddRequest struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

// AddResponse holds newly added task id.
type AddResponse struct {
	Id     string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status ResponseStatus `protobuf:"varint,2,opt,name=status,enum=kudu.task.ResponseStatus" json:"status,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

// RemoveRequest holds task id which is going to be deleted.
type RemoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// RemoveResponse holds remove task response status.
type RemoveResponse struct {
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,enum=kudu.task.ResponseStatus" json:"status,omitempty"`
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

func init() {
	proto.RegisterType((*Task)(nil), "kudu.task.Task")
	proto.RegisterType((*TodayTasksRequest)(nil), "kudu.task.TodayTasksRequest")
	proto.RegisterType((*TodayTasksResponse)(nil), "kudu.task.TodayTasksResponse")
	proto.RegisterType((*AddRequest)(nil), "kudu.task.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "kudu.task.AddResponse")
	proto.RegisterType((*RemoveRequest)(nil), "kudu.task.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "kudu.task.RemoveResponse")
	proto.RegisterEnum("kudu.task.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	TodayTasks(ctx context.Context, in *TodayTasksRequest, opts ...grpc.CallOption) (*TodayTasksResponse, error)
	AddTask(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	RemoveTask(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) TodayTasks(ctx context.Context, in *TodayTasksRequest, opts ...grpc.CallOption) (*TodayTasksResponse, error) {
	out := new(TodayTasksResponse)
	err := grpc.Invoke(ctx, "/kudu.task.TaskService/TodayTasks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AddTask(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/kudu.task.TaskService/AddTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RemoveTask(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc.Invoke(ctx, "/kudu.task.TaskService/RemoveTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	TodayTasks(context.Context, *TodayTasksRequest) (*TodayTasksResponse, error)
	AddTask(context.Context, *AddRequest) (*AddResponse, error)
	RemoveTask(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_TodayTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodayTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TodayTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.task.TaskService/TodayTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TodayTasks(ctx, req.(*TodayTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.task.TaskService/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddTask(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.task.TaskService/RemoveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RemoveTask(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudu.task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TodayTasks",
			Handler:    _TaskService_TodayTasks_Handler,
		},
		{
			MethodName: "AddTask",
			Handler:    _TaskService_AddTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _TaskService_RemoveTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/task/task.proto",
}

func init() { proto.RegisterFile("protobuf/task/task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0xdf, 0x8f, 0xd2, 0x40,
	0x10, 0xbe, 0xf2, 0x9b, 0x21, 0x62, 0x6f, 0xa3, 0x97, 0x05, 0xcf, 0x48, 0x6a, 0x4c, 0xc8, 0x3d,
	0x40, 0x0e, 0xdf, 0x7c, 0xab, 0x80, 0x09, 0xe1, 0xae, 0x98, 0x2d, 0x68, 0xe2, 0x4b, 0x53, 0xd8,
	0x15, 0x09, 0xb4, 0x45, 0x76, 0x7b, 0x89, 0xff, 0x9b, 0xff, 0x89, 0xff, 0x8c, 0xd9, 0x29, 0x3d,
	0x7a, 0xcd, 0x99, 0x98, 0x7b, 0x21, 0x33, 0xdf, 0x7c, 0xf3, 0xcd, 0xc7, 0x4c, 0x17, 0xe8, 0xfe,
	0x10, 0xa9, 0x68, 0x19, 0x7f, 0xef, 0x2b, 0x5f, 0x6e, 0xf1, 0xa7, 0x87, 0x10, 0xa9, 0x6f, 0x63,
	0x1e, 0xf7, 0x34, 0x60, 0xfd, 0x36, 0xa0, 0x34, 0xf7, 0xe5, 0x96, 0x34, 0xa1, 0xb0, 0xe1, 0xd4,
	0xe8, 0x18, 0xdd, 0x3a, 0x2b, 0x6c, 0x38, 0x79, 0x05, 0x75, 0x4d, 0xf0, 0x42, 0x3f, 0x10, 0xb4,
	0x80, 0x70, 0x4d, 0x03, 0x8e, 0x1f, 0x08, 0x62, 0x42, 0x31, 0x3e, 0xec, 0x68, 0x11, 0x61, 0x1d,
	0x12, 0x02, 0x25, 0xe5, 0xaf, 0x25, 0x2d, 0x21, 0x84, 0x31, 0x79, 0x01, 0xe5, 0x30, 0x52, 0x42,
	0xd2, 0x32, 0x82, 0x49, 0x42, 0x5a, 0x50, 0xc3, 0xc0, 0x0b, 0x38, 0xad, 0x60, 0xa1, 0x8a, 0xf9,
	0x2d, 0xd7, 0x22, 0xdc, 0x57, 0x82, 0x56, 0x13, 0x11, 0x1d, 0x93, 0x4b, 0xa8, 0xaf, 0xa2, 0x60,
	0xbf, 0x13, 0x4a, 0x70, 0x5a, 0xeb, 0x18, 0xdd, 0x1a, 0x3b, 0x01, 0xd6, 0x08, 0xce, 0xe7, 0x11,
	0xf7, 0x7f, 0xe9, 0xbf, 0x20, 0x99, 0xf8, 0x19, 0x0b, 0xa9, 0x1e, 0x5a, 0x37, 0x72, 0xd6, 0x53,
	0xa3, 0x85, 0x93, 0x51, 0x2b, 0x04, 0x92, 0x55, 0x91, 0xfb, 0x28, 0x94, 0x82, 0xbc, 0x83, 0xb2,
	0xee, 0x92, 0xd4, 0xe8, 0x14, 0xbb, 0x8d, 0xc1, 0xf3, 0xde, 0xfd, 0xd6, 0x7a, 0x9a, 0xc8, 0x92,
	0x2a, 0xb9, 0x86, 0x8a, 0x54, 0xbe, 0x8a, 0x13, 0xc9, 0xe6, 0xa0, 0x95, 0xe1, 0xa5, 0x5a, 0x2e,
	0x12, 0xd8, 0x91, 0x68, 0x5d, 0x03, 0xd8, 0x9c, 0xa7, 0x76, 0xdf, 0x6a, 0x47, 0x72, 0x8b, 0x4e,
	0x1f, 0x19, 0x83, 0x45, 0xeb, 0x33, 0x34, 0xb0, 0xe5, 0xe8, 0x2d, 0x7f, 0xad, 0x27, 0x98, 0x78,
	0x03, 0xcf, 0x98, 0x08, 0xa2, 0x3b, 0x91, 0xfa, 0xc8, 0x69, 0x5a, 0x43, 0x68, 0xa6, 0x84, 0xe3,
	0xd4, 0xd3, 0x14, 0xe3, 0x3f, 0xa7, 0x5c, 0x85, 0x5a, 0x24, 0x5b, 0x21, 0x0d, 0xa8, 0x2e, 0x9c,
	0xa9, 0x33, 0xfb, 0xea, 0x98, 0x67, 0x3a, 0x71, 0x17, 0xc3, 0xe1, 0xd8, 0x75, 0x4d, 0x83, 0x10,
	0x68, 0x4e, 0x9c, 0xf9, 0x98, 0x39, 0xf6, 0x8d, 0x37, 0x66, 0x6c, 0xc6, 0xcc, 0x02, 0x69, 0xc3,
	0xc5, 0xdc, 0x76, 0xa7, 0xde, 0xc4, 0xf9, 0x62, 0xdf, 0x4c, 0x46, 0x1e, 0x26, 0x8e, 0x7d, 0x3b,
	0x36, 0x4d, 0xcd, 0x4f, 0xd2, 0xd9, 0xdc, 0xfb, 0x34, 0x5b, 0x38, 0x23, 0xf3, 0x7c, 0xf0, 0xc7,
	0x80, 0x86, 0x5e, 0x9b, 0x2b, 0x0e, 0x77, 0x9b, 0x95, 0x20, 0x53, 0x80, 0xd3, 0x69, 0xc9, 0x65,
	0x76, 0xb9, 0xf9, 0xef, 0xa6, 0xfd, 0xfa, 0x1f, 0xd5, 0xc4, 0xbe, 0x75, 0x46, 0x3e, 0x40, 0xd5,
	0xe6, 0x1c, 0x9f, 0xcb, 0xcb, 0x0c, 0xf7, 0x74, 0xcb, 0xf6, 0x45, 0x1e, 0xbe, 0xef, 0x1d, 0x02,
	0x24, 0xdb, 0xc4, 0x76, 0xfa, 0x60, 0x73, 0x99, 0x2b, 0xb4, 0x5b, 0x8f, 0x54, 0x52, 0x91, 0x8f,
	0x57, 0xdf, 0xba, 0xeb, 0x8d, 0xfa, 0x11, 0x2f, 0x7b, 0xab, 0x28, 0xe8, 0x1f, 0x42, 0xde, 0xd7,
	0xe4, 0xfe, 0x3a, 0xda, 0xf9, 0xe1, 0xba, 0x8f, 0x8f, 0x7b, 0x2d, 0x42, 0x7c, 0xea, 0xcb, 0x0a,
	0xa6, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe8, 0x1a, 0x60, 0x07, 0x04, 0x00, 0x00,
}
