// Code generated by protoc-gen-go.
// source: item/item.proto
// DO NOT EDIT!

/*
Package item is a generated protocol buffer package.

It is generated from these files:
	item/item.proto

It has these top-level messages:
	Item
	ListRequest
	ListResponse
	AddRequest
	AddResponse
	GetRequest
	GetResponse
*/
package item

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import kudu_type "github.com/rnd/kudu/golang/protogen/type/date"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Item holds item information.
type Item struct {
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Goal      string                     `protobuf:"bytes,2,opt,name=goal" json:"goal,omitempty"`
	Url       string                     `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Tag       string                     `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	Notes     string                     `protobuf:"bytes,5,opt,name=notes" json:"notes,omitempty"`
	NotesMd   string                     `protobuf:"bytes,6,opt,name=notes_md,json=notesMd" json:"notes_md,omitempty"`
	Date      *kudu_type.Date            `protobuf:"bytes,7,opt,name=date" json:"date,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Item) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Item) GetNotesMd() string {
	if m != nil {
		return m.NotesMd
	}
	return ""
}

func (m *Item) GetDate() *kudu_type.Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Item) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// ListRequest holds item list filter value.
type ListRequest struct {
	Date *kudu_type.Date `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
	Goal string          `protobuf:"bytes,2,opt,name=goal" json:"goal,omitempty"`
	Tag  string          `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListRequest) GetDate() *kudu_type.Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ListRequest) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *ListRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// ListResponse holds item list information.
type ListResponse struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// AddRequest holds information of item that is going to be added.
type AddRequest struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// AddResponse holds newly added item id.
type AddResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetRequest holds item filter value.
type GetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetResponse holds item information.
type GetResponse struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "kudu.item.Item")
	proto.RegisterType((*ListRequest)(nil), "kudu.item.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "kudu.item.ListResponse")
	proto.RegisterType((*AddRequest)(nil), "kudu.item.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "kudu.item.AddResponse")
	proto.RegisterType((*GetRequest)(nil), "kudu.item.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "kudu.item.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ItemService service

type ItemServiceClient interface {
	ListItem(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	AddItem(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	GetItem(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) ListItem(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/ListItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) AddItem(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/AddItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItem(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/GetItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ItemService service

type ItemServiceServer interface {
	ListItem(context.Context, *ListRequest) (*ListResponse, error)
	AddItem(context.Context, *AddRequest) (*AddResponse, error)
	GetItem(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_ListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/ListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListItem(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).AddItem(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItem(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudu.item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItem",
			Handler:    _ItemService_ListItem_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _ItemService_AddItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ItemService_GetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item/item.proto",
}

func init() { proto.RegisterFile("item/item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x8b, 0xd4, 0x30,
	0x14, 0xdf, 0xce, 0x74, 0x76, 0x66, 0x5e, 0xc5, 0x91, 0xa0, 0x6b, 0x2c, 0x8a, 0x43, 0x44, 0x18,
	0x3c, 0xa4, 0x38, 0x22, 0x88, 0xe0, 0x61, 0x45, 0x58, 0x04, 0xbd, 0x54, 0x0f, 0xe2, 0x45, 0x3a,
	0x9b, 0x67, 0x2c, 0xb6, 0x4d, 0x6d, 0x53, 0xc1, 0xef, 0xe7, 0xe7, 0xf0, 0xb3, 0x48, 0x5e, 0x76,
	0xdb, 0xee, 0x0c, 0xca, 0x5e, 0x4a, 0xde, 0xef, 0x4f, 0xde, 0xfb, 0x25, 0x0d, 0xac, 0x72, 0x8b,
	0x65, 0xe2, 0x3e, 0xb2, 0x6e, 0x8c, 0x35, 0x6c, 0xf9, 0xbd, 0x53, 0x9d, 0x74, 0x40, 0xbc, 0xb2,
	0xbf, 0x6a, 0x4c, 0x54, 0x66, 0xd1, 0x73, 0xf1, 0x43, 0x6d, 0x8c, 0x2e, 0x30, 0xa1, 0x6a, 0xd7,
	0x7d, 0x4d, 0x6c, 0x5e, 0x62, 0x6b, 0xb3, 0xb2, 0xf6, 0x02, 0xf1, 0x27, 0x80, 0xf0, 0xad, 0xc5,
	0x92, 0xdd, 0x84, 0x49, 0xae, 0x78, 0xb0, 0x0e, 0x36, 0xcb, 0x74, 0x92, 0x2b, 0xc6, 0x20, 0xd4,
	0x26, 0x2b, 0xf8, 0x84, 0x10, 0x5a, 0xb3, 0x5b, 0x30, 0xed, 0x9a, 0x82, 0x4f, 0x09, 0x72, 0x4b,
	0x87, 0xd8, 0x4c, 0xf3, 0xd0, 0x23, 0x36, 0xd3, 0xec, 0x36, 0xcc, 0x2a, 0x63, 0xb1, 0xe5, 0x33,
	0xc2, 0x7c, 0xc1, 0xee, 0xc1, 0x82, 0x16, 0x5f, 0x4a, 0xc5, 0x8f, 0x89, 0x98, 0x53, 0xfd, 0x5e,
	0xb1, 0x47, 0x10, 0xba, 0x81, 0xf9, 0x7c, 0x1d, 0x6c, 0xa2, 0xed, 0x4a, 0x52, 0x1a, 0x97, 0x43,
	0xbe, 0xc9, 0x2c, 0xa6, 0x44, 0xb2, 0x17, 0xb0, 0xec, 0x27, 0xe7, 0x0b, 0x52, 0xc6, 0xd2, 0x67,
	0x93, 0x97, 0xd9, 0xe4, 0xc7, 0x4b, 0x45, 0x3a, 0x88, 0xc5, 0x27, 0x88, 0xde, 0xe5, 0xad, 0x4d,
	0xf1, 0x47, 0x87, 0xad, 0xed, 0xbb, 0x05, 0xff, 0xeb, 0xf6, 0x8f, 0xec, 0x2e, 0xe9, 0xb4, 0x4f,
	0x2a, 0x9e, 0xc3, 0x0d, 0xbf, 0x73, 0x5b, 0x9b, 0xaa, 0x45, 0xf6, 0x18, 0x66, 0xee, 0x12, 0x5a,
	0x1e, 0xac, 0xa7, 0xc3, 0xde, 0x74, 0x51, 0xee, 0x84, 0x53, 0xcf, 0x8a, 0xa7, 0x00, 0xa7, 0x4a,
	0x8d, 0xe6, 0x71, 0xf0, 0xd5, 0x79, 0x06, 0x0f, 0x91, 0xe2, 0x01, 0x44, 0x64, 0xb9, 0x68, 0xb4,
	0x77, 0x55, 0xe2, 0x3e, 0xc0, 0x19, 0xf6, 0x09, 0xf7, 0xd9, 0x2d, 0x44, 0xc4, 0x5e, 0x98, 0xaf,
	0xd3, 0x70, 0xfb, 0x3b, 0x80, 0xc8, 0x95, 0x1f, 0xb0, 0xf9, 0x99, 0x9f, 0x23, 0x7b, 0x05, 0x0b,
	0x17, 0x95, 0x7e, 0x94, 0x93, 0x91, 0x65, 0x74, 0xb2, 0xf1, 0xdd, 0x03, 0xdc, 0x77, 0x14, 0x47,
	0xec, 0x25, 0xcc, 0x4f, 0x95, 0x22, 0xf7, 0x9d, 0x91, 0x6a, 0x38, 0x86, 0xf8, 0x64, 0x1f, 0x1e,
	0x7b, 0xcf, 0xd0, 0x1e, 0x78, 0x87, 0xc0, 0x57, 0xbc, 0xa3, 0xa4, 0xe2, 0xe8, 0xf5, 0x93, 0xcf,
	0x1b, 0x9d, 0xdb, 0x6f, 0xdd, 0x4e, 0x9e, 0x9b, 0x32, 0x69, 0x2a, 0x95, 0x38, 0x65, 0xa2, 0x4d,
	0x91, 0x55, 0xda, 0xbf, 0x09, 0x8d, 0x15, 0xbd, 0xa5, 0xdd, 0x31, 0x95, 0xcf, 0xfe, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0xd6, 0x41, 0xa9, 0x5f, 0x03, 0x00, 0x00,
}
