// Code generated by protoc-gen-go.
// source: protobuf/item/item.proto
// DO NOT EDIT!

/*
Package item is a generated protocol buffer package.

It is generated from these files:
	protobuf/item/item.proto

It has these top-level messages:
	Item
	TodayItemsRequest
	TodayItemsResponse
	AddRequest
	AddResponse
	RemoveRequest
	RemoveResponse
*/
package item

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResponseStatus is response status enum.
type ResponseStatus int32

const (
	ResponseStatus_UNKNOWN           ResponseStatus = 0
	ResponseStatus_SUCCESS           ResponseStatus = 1
	ResponseStatus_INTERNAL_ERROR    ResponseStatus = 2
	ResponseStatus_ITEM_INVALID_GOAL ResponseStatus = 16
	ResponseStatus_ITEM_NOT_FOUND    ResponseStatus = 17
)

var ResponseStatus_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUCCESS",
	2:  "INTERNAL_ERROR",
	16: "ITEM_INVALID_GOAL",
	17: "ITEM_NOT_FOUND",
}
var ResponseStatus_value = map[string]int32{
	"UNKNOWN":           0,
	"SUCCESS":           1,
	"INTERNAL_ERROR":    2,
	"ITEM_INVALID_GOAL": 16,
	"ITEM_NOT_FOUND":    17,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}
func (ResponseStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Item holds item information.
type Item struct {
	Id          string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Goal        string                     `protobuf:"bytes,2,opt,name=goal" json:"goal,omitempty"`
	Url         string                     `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Tags        string                     `protobuf:"bytes,4,opt,name=tags" json:"tags,omitempty"`
	Notes       string                     `protobuf:"bytes,5,opt,name=notes" json:"notes,omitempty"`
	NotesMd     string                     `protobuf:"bytes,6,opt,name=notes_md,json=notesMd" json:"notes_md,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	CompletedAt *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt" json:"completed_at,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Item) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Item) GetNotesMd() string {
	if m != nil {
		return m.NotesMd
	}
	return ""
}

func (m *Item) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Item) GetCompletedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

// TodayItemsRequest holds information which can be used
// to filter today item list.
type TodayItemsRequest struct {
	Goal string `protobuf:"bytes,1,opt,name=goal" json:"goal,omitempty"`
	Tags string `protobuf:"bytes,2,opt,name=tags" json:"tags,omitempty"`
}

func (m *TodayItemsRequest) Reset()                    { *m = TodayItemsRequest{} }
func (m *TodayItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*TodayItemsRequest) ProtoMessage()               {}
func (*TodayItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TodayItemsRequest) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *TodayItemsRequest) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

// TodayItemsResponse holds today item list.
type TodayItemsResponse struct {
	Items  []*Item        `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Status ResponseStatus `protobuf:"varint,2,opt,name=status,enum=kudu.item.ResponseStatus" json:"status,omitempty"`
}

func (m *TodayItemsResponse) Reset()                    { *m = TodayItemsResponse{} }
func (m *TodayItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*TodayItemsResponse) ProtoMessage()               {}
func (*TodayItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodayItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TodayItemsResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

// AddRequest holds information of item which is going to be added.
type AddRequest struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// AddResponse holds newly added item id.
type AddResponse struct {
	Id     string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status ResponseStatus `protobuf:"varint,2,opt,name=status,enum=kudu.item.ResponseStatus" json:"status,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

// RemoveRequest holds item id which is goint to be deleted.
type RemoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// RemoveResponse holds remove item response status.
type RemoveResponse struct {
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,enum=kudu.item.ResponseStatus" json:"status,omitempty"`
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

func init() {
	proto.RegisterType((*Item)(nil), "kudu.item.Item")
	proto.RegisterType((*TodayItemsRequest)(nil), "kudu.item.TodayItemsRequest")
	proto.RegisterType((*TodayItemsResponse)(nil), "kudu.item.TodayItemsResponse")
	proto.RegisterType((*AddRequest)(nil), "kudu.item.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "kudu.item.AddResponse")
	proto.RegisterType((*RemoveRequest)(nil), "kudu.item.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "kudu.item.RemoveResponse")
	proto.RegisterEnum("kudu.item.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ItemService service

type ItemServiceClient interface {
	TodayItems(ctx context.Context, in *TodayItemsRequest, opts ...grpc.CallOption) (*TodayItemsResponse, error)
	AddItem(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	RemoveItem(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) TodayItems(ctx context.Context, in *TodayItemsRequest, opts ...grpc.CallOption) (*TodayItemsResponse, error) {
	out := new(TodayItemsResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/TodayItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) AddItem(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/AddItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) RemoveItem(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc.Invoke(ctx, "/kudu.item.ItemService/RemoveItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ItemService service

type ItemServiceServer interface {
	TodayItems(context.Context, *TodayItemsRequest) (*TodayItemsResponse, error)
	AddItem(context.Context, *AddRequest) (*AddResponse, error)
	RemoveItem(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_TodayItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodayItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).TodayItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/TodayItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).TodayItems(ctx, req.(*TodayItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).AddItem(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.ItemService/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).RemoveItem(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudu.item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TodayItems",
			Handler:    _ItemService_TodayItems_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _ItemService_AddItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _ItemService_RemoveItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/item/item.proto",
}

func init() { proto.RegisterFile("protobuf/item/item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0x5d, 0x8f, 0xd2, 0x4c,
	0x14, 0xc7, 0xb7, 0xbc, 0x2e, 0xa7, 0xcf, 0x83, 0x65, 0xe2, 0x9a, 0x81, 0x68, 0x96, 0xd4, 0x98,
	0x90, 0xbd, 0x28, 0x59, 0xbc, 0x52, 0xe3, 0x45, 0x65, 0xd1, 0x90, 0x65, 0x8b, 0x19, 0x40, 0x13,
	0x6f, 0x9a, 0xc2, 0x8c, 0xb5, 0x91, 0x76, 0x90, 0x4e, 0x37, 0xf1, 0xb3, 0xfa, 0x51, 0xbc, 0x31,
	0x33, 0x7d, 0xa1, 0xe2, 0x1a, 0x8d, 0x37, 0x64, 0xe6, 0x9c, 0xdf, 0x39, 0xe7, 0x7f, 0xce, 0xa1,
	0x03, 0x78, 0xb7, 0xe7, 0x82, 0xaf, 0x93, 0x8f, 0xc3, 0x40, 0xb0, 0x50, 0xfd, 0x58, 0xca, 0x84,
	0x5a, 0x9f, 0x13, 0x9a, 0x58, 0xd2, 0xd0, 0x3b, 0xf7, 0x39, 0xf7, 0xb7, 0x6c, 0x58, 0xb0, 0x22,
	0x08, 0x59, 0x2c, 0xbc, 0x70, 0x97, 0xb2, 0xe6, 0x77, 0x0d, 0x6a, 0x53, 0xc1, 0x42, 0xd4, 0x86,
	0x4a, 0x40, 0xb1, 0xd6, 0xd7, 0x06, 0x2d, 0x52, 0x09, 0x28, 0x42, 0x50, 0xf3, 0xb9, 0xb7, 0xc5,
	0x15, 0x65, 0x51, 0x67, 0x64, 0x40, 0x35, 0xd9, 0x6f, 0x71, 0x55, 0x99, 0xe4, 0x51, 0x52, 0xc2,
	0xf3, 0x63, 0x5c, 0x4b, 0x29, 0x79, 0x46, 0xf7, 0xa1, 0x1e, 0x71, 0xc1, 0x62, 0x5c, 0x57, 0xc6,
	0xf4, 0x82, 0xba, 0x70, 0xaa, 0x0e, 0x6e, 0x48, 0x71, 0x43, 0x39, 0x9a, 0xea, 0x7e, 0x43, 0xd1,
	0x33, 0x80, 0xcd, 0x9e, 0x79, 0x82, 0x51, 0xd7, 0x13, 0xb8, 0xd9, 0xd7, 0x06, 0xfa, 0xa8, 0x67,
	0xa5, 0xca, 0xad, 0x5c, 0xb9, 0xb5, 0xcc, 0x95, 0x93, 0x56, 0x46, 0xdb, 0x02, 0xbd, 0x84, 0xff,
	0x36, 0x3c, 0xdc, 0x6d, 0x59, 0x16, 0x7c, 0xfa, 0xc7, 0x60, 0xbd, 0xe0, 0x6d, 0x61, 0xbe, 0x80,
	0xce, 0x92, 0x53, 0xef, 0xab, 0x9c, 0x40, 0x4c, 0xd8, 0x97, 0x84, 0xc5, 0xa2, 0xe8, 0x5c, 0x2b,
	0x75, 0x9e, 0xf7, 0x59, 0x39, 0xf4, 0x69, 0x46, 0x80, 0xca, 0xc1, 0xf1, 0x8e, 0x47, 0x31, 0x43,
	0x4f, 0xa0, 0x2e, 0x27, 0x1f, 0x63, 0xad, 0x5f, 0x1d, 0xe8, 0xa3, 0x7b, 0x56, 0xb1, 0x0c, 0x4b,
	0x82, 0x24, 0xf5, 0xa2, 0x4b, 0x68, 0xc4, 0xc2, 0x13, 0x49, 0x9a, 0xb2, 0x3d, 0xea, 0x96, 0xb8,
	0x3c, 0xd7, 0x42, 0x01, 0x24, 0x03, 0xcd, 0x4b, 0x00, 0x9b, 0xd2, 0x5c, 0xe5, 0x63, 0xa8, 0x49,
	0x58, 0xa9, 0xbc, 0xa3, 0x8c, 0x72, 0x9a, 0x6f, 0x41, 0x57, 0x21, 0x99, 0xb6, 0xe3, 0x1d, 0xff,
	0x83, 0x88, 0x73, 0xf8, 0x9f, 0xb0, 0x90, 0xdf, 0xb2, 0x5c, 0xc7, 0x51, 0x4e, 0x73, 0x0c, 0xed,
	0x1c, 0xc8, 0xaa, 0x1e, 0xaa, 0x68, 0x7f, 0x59, 0xe5, 0x22, 0x90, 0x49, 0xca, 0x1e, 0xa4, 0x43,
	0x73, 0xe5, 0x5c, 0x3b, 0xf3, 0xf7, 0x8e, 0x71, 0x22, 0x2f, 0x8b, 0xd5, 0x78, 0x3c, 0x59, 0x2c,
	0x0c, 0x0d, 0x21, 0x68, 0x4f, 0x9d, 0xe5, 0x84, 0x38, 0xf6, 0xcc, 0x9d, 0x10, 0x32, 0x27, 0x46,
	0x05, 0x9d, 0x41, 0x67, 0xba, 0x9c, 0xdc, 0xb8, 0x53, 0xe7, 0x9d, 0x3d, 0x9b, 0x5e, 0xb9, 0x6f,
	0xe6, 0xf6, 0xcc, 0x30, 0x14, 0x2a, 0xcd, 0xce, 0x7c, 0xe9, 0xbe, 0x9e, 0xaf, 0x9c, 0x2b, 0xa3,
	0x33, 0xfa, 0xa6, 0x81, 0x2e, 0x27, 0xb6, 0x60, 0xfb, 0xdb, 0x60, 0xc3, 0xd0, 0x35, 0xc0, 0x61,
	0xab, 0xe8, 0x61, 0x49, 0xeb, 0x2f, 0xff, 0x94, 0xde, 0xa3, 0xdf, 0x78, 0x53, 0xe5, 0xe6, 0x09,
	0x7a, 0x0e, 0x4d, 0x9b, 0x52, 0xf5, 0x7d, 0x9d, 0x95, 0xd8, 0xc3, 0x1a, 0x7b, 0x0f, 0x8e, 0xcd,
	0x45, 0xec, 0x18, 0x20, 0x1d, 0xa4, 0x0a, 0xc7, 0x3f, 0x0d, 0xad, 0xb4, 0x80, 0x5e, 0xf7, 0x0e,
	0x4f, 0x9e, 0xe4, 0xd5, 0xc5, 0x87, 0x81, 0x1f, 0x88, 0x4f, 0xc9, 0xda, 0xda, 0xf0, 0x70, 0xb8,
	0x8f, 0xe8, 0x50, 0xc2, 0x43, 0x9f, 0x6f, 0xbd, 0xc8, 0x4f, 0x5f, 0x05, 0x9f, 0x45, 0xea, 0xf1,
	0x58, 0x37, 0xd4, 0xf5, 0xe9, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xf3, 0xe5, 0x56, 0x59,
	0x04, 0x00, 0x00,
}
